-- Controlled super-admin updates for locked shop identity/contact fields.
--
-- Merchants cannot edit approved shop name, phone, or WhatsApp directly. This
-- RPC gives super admins a narrow audited path for verified support requests.

CREATE SCHEMA IF NOT EXISTS private;

REVOKE ALL ON SCHEMA private FROM PUBLIC;
GRANT USAGE ON SCHEMA private TO anon, authenticated, service_role;

CREATE TABLE IF NOT EXISTS private.shop_identity_update_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id bigint NOT NULL,
  staff_id uuid NOT NULL,
  previous_values jsonb NOT NULL,
  new_values jsonb NOT NULL,
  reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS shop_identity_update_audit_shop_created_idx
  ON private.shop_identity_update_audit (shop_id, created_at DESC);

CREATE OR REPLACE FUNCTION private.ctm_update_shop_locked_contact_fields(
  p_shop_id bigint,
  p_name text,
  p_phone text,
  p_whatsapp text DEFAULT NULL::text,
  p_reason text DEFAULT NULL::text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_actor_id uuid := (SELECT auth.uid());
  v_shop public.shops%rowtype;
  v_updated_shop public.shops%rowtype;
  v_name text := nullif(left(trim(coalesce(p_name, '')), 120), '');
  v_phone text := nullif(regexp_replace(trim(coalesce(p_phone, '')), '\s+', '', 'g'), '');
  v_whatsapp text := nullif(regexp_replace(trim(coalesce(p_whatsapp, '')), '\s+', '', 'g'), '');
  v_reason text := nullif(left(trim(coalesce(p_reason, '')), 500), '');
  v_previous jsonb;
  v_next jsonb;
BEGIN
  IF NOT private.ctm_has_super_staff_access() THEN
    RAISE EXCEPTION 'Only super admins can update locked shop identity fields.' USING ERRCODE = '42501';
  END IF;

  IF p_shop_id IS NULL OR p_shop_id <= 0 THEN
    RAISE EXCEPTION 'A valid shop id is required.' USING ERRCODE = '22023';
  END IF;

  IF v_name IS NULL OR length(v_name) < 2 THEN
    RAISE EXCEPTION 'Business name must be at least 2 characters.' USING ERRCODE = '22023';
  END IF;

  IF v_phone IS NULL OR v_phone !~ '^(0[0-9]{10}|[0-9]{10}|\+[0-9]{11,15})$' THEN
    RAISE EXCEPTION 'Enter a valid phone number.' USING ERRCODE = '22023';
  END IF;

  IF v_whatsapp IS NOT NULL AND v_whatsapp !~ '^(0[0-9]{10}|[0-9]{10}|\+[0-9]{11,15})$' THEN
    RAISE EXCEPTION 'Enter a valid WhatsApp number.' USING ERRCODE = '22023';
  END IF;

  SELECT *
  INTO v_shop
  FROM public.shops
  WHERE id = p_shop_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Shop not found.' USING ERRCODE = 'P0002';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.shops s
    WHERE s.id <> p_shop_id
      AND lower(trim(s.name)) = lower(v_name)
  ) THEN
    RAISE EXCEPTION 'Another shop already uses this business name.' USING ERRCODE = '23505';
  END IF;

  v_previous := jsonb_build_object(
    'name', v_shop.name,
    'phone', v_shop.phone,
    'whatsapp', v_shop.whatsapp
  );

  UPDATE public.shops
  SET
    name = v_name,
    phone = v_phone,
    whatsapp = v_whatsapp
  WHERE id = p_shop_id
  RETURNING *
  INTO v_updated_shop;

  v_next := jsonb_build_object(
    'name', v_updated_shop.name,
    'phone', v_updated_shop.phone,
    'whatsapp', v_updated_shop.whatsapp
  );

  INSERT INTO private.shop_identity_update_audit (
    shop_id,
    staff_id,
    previous_values,
    new_values,
    reason
  )
  VALUES (
    p_shop_id,
    v_actor_id,
    v_previous,
    v_next,
    v_reason
  );

  IF v_updated_shop.owner_id IS NOT NULL THEN
    PERFORM public.push_user_notification(
      v_updated_shop.owner_id,
      'Shop contact details updated',
      'A CTMerchant super admin updated the locked business name or contact details for "' || v_updated_shop.name || '".',
      'shop',
      '/merchant-settings?shop_id=' || v_updated_shop.id::text
    );
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'shop', to_jsonb(v_updated_shop),
    'previous_values', v_previous,
    'new_values', v_next
  );
END;
$$;

REVOKE ALL ON FUNCTION private.ctm_update_shop_locked_contact_fields(bigint, text, text, text, text)
  FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION private.ctm_update_shop_locked_contact_fields(bigint, text, text, text, text)
  TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.ctm_update_shop_locked_contact_fields(
  p_shop_id bigint,
  p_name text,
  p_phone text,
  p_whatsapp text DEFAULT NULL::text,
  p_reason text DEFAULT NULL::text
)
RETURNS jsonb
LANGUAGE sql
SET search_path TO 'public', 'private', 'pg_temp'
AS $$
  SELECT private.ctm_update_shop_locked_contact_fields(
    p_shop_id,
    p_name,
    p_phone,
    p_whatsapp,
    p_reason
  );
$$;

REVOKE ALL ON FUNCTION public.ctm_update_shop_locked_contact_fields(bigint, text, text, text, text)
  FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ctm_update_shop_locked_contact_fields(bigint, text, text, text, text)
  TO authenticated, service_role;
