create table if not exists public.site_visit_events (
  id bigint generated by default as identity primary key,
  visitor_key text not null,
  session_key text not null,
  page_path text not null,
  referrer_path text,
  user_id uuid references public.profiles(id) on delete set null,
  is_authenticated boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_site_visit_events_created_at
  on public.site_visit_events (created_at desc);

create index if not exists idx_site_visit_events_page_path_created_at
  on public.site_visit_events (page_path, created_at desc);

create index if not exists idx_site_visit_events_visitor_key_created_at
  on public.site_visit_events (visitor_key, created_at desc);

alter table public.site_visit_events enable row level security;

create or replace function public.is_staff_member()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.staff_profiles sp
    where sp.id = auth.uid()
  );
$$;

create or replace function public.record_site_visit(
  p_session_key text,
  p_visitor_key text,
  p_page_path text,
  p_referrer_path text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session_key text := nullif(trim(coalesce(p_session_key, '')), '');
  v_page_path text := left(coalesce(nullif(trim(p_page_path), ''), '/'), 300);
  v_referrer_path text := left(nullif(trim(coalesce(p_referrer_path, '')), ''), 300);
  v_user_id uuid := auth.uid();
  v_is_authenticated boolean := v_user_id is not null;
  v_visitor_key text;
begin
  if v_session_key is null then
    return;
  end if;

  v_visitor_key := case
    when v_is_authenticated then 'user:' || v_user_id::text
    when nullif(trim(coalesce(p_visitor_key, '')), '') is not null then left(trim(p_visitor_key), 120)
    else 'session:' || md5(v_session_key)
  end;

  if exists (
    select 1
    from public.site_visit_events sve
    where sve.session_key = v_session_key
      and sve.page_path = v_page_path
      and sve.created_at >= now() - interval '20 minutes'
  ) then
    return;
  end if;

  insert into public.site_visit_events (
    visitor_key,
    session_key,
    page_path,
    referrer_path,
    user_id,
    is_authenticated
  )
  values (
    v_visitor_key,
    v_session_key,
    v_page_path,
    v_referrer_path,
    v_user_id,
    v_is_authenticated
  );
end;
$$;

create or replace function public.staff_user_activity_summary(
  p_inactive_days integer default 180,
  p_city_id bigint default null
)
returns table (
  user_id uuid,
  email text,
  full_name text,
  city_id bigint,
  city_name text,
  state_name text,
  account_created_at timestamptz,
  last_sign_in_at timestamptz,
  last_seen_at timestamptz,
  inactivity_days integer,
  is_inactive boolean,
  is_suspended boolean,
  shop_count integer,
  shops jsonb
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_staff_member() then
    raise exception 'Access denied'
      using errcode = '42501';
  end if;

  return query
  with shop_rollup as (
    select
      s.owner_id,
      count(*)::integer as shop_count,
      coalesce(
        jsonb_agg(
          jsonb_build_object(
            'shop_id', s.id,
            'shop_name', s.name,
            'unique_id', s.unique_id,
            'status', s.status,
            'is_open', s.is_open,
            'city_id', s.city_id
          )
          order by s.created_at desc
        ) filter (where s.id is not null),
        '[]'::jsonb
      ) as shops
    from public.shops s
    group by s.owner_id
  )
  select
    u.id as user_id,
    u.email::text as email,
    p.full_name,
    p.city_id,
    c.name as city_name,
    c.state as state_name,
    u.created_at as account_created_at,
    u.last_sign_in_at,
    coalesce(u.last_sign_in_at, u.created_at) as last_seen_at,
    greatest(
      floor(
        extract(epoch from (now() - coalesce(u.last_sign_in_at, u.created_at))) / 86400
      )::integer,
      0
    ) as inactivity_days,
    (
      coalesce(u.last_sign_in_at, u.created_at)
      <= now() - make_interval(days => greatest(coalesce(p_inactive_days, 180), 1))
    ) as is_inactive,
    coalesce(p.is_suspended, false) as is_suspended,
    coalesce(sr.shop_count, 0) as shop_count,
    coalesce(sr.shops, '[]'::jsonb) as shops
  from auth.users u
  left join public.profiles p
    on p.id = u.id
  left join public.cities c
    on c.id = p.city_id
  left join shop_rollup sr
    on sr.owner_id = u.id
  left join public.staff_profiles sp
    on sp.id = u.id
  where sp.id is null
    and u.email is not null
    and (p_city_id is null or p.city_id = p_city_id)
  order by
    (
      coalesce(u.last_sign_in_at, u.created_at)
      <= now() - make_interval(days => greatest(coalesce(p_inactive_days, 180), 1))
    ) desc,
    coalesce(u.last_sign_in_at, u.created_at) asc,
    u.created_at desc;
end;
$$;

create or replace function public.staff_site_visit_daily(
  p_days integer default 30
)
returns table (
  visit_date date,
  total_visits bigint,
  unique_visitors bigint,
  authenticated_visits bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_staff_member() then
    raise exception 'Access denied'
      using errcode = '42501';
  end if;

  return query
  select
    (timezone('Africa/Lagos', sve.created_at))::date as visit_date,
    count(*)::bigint as total_visits,
    count(distinct sve.visitor_key)::bigint as unique_visitors,
    count(*) filter (where sve.is_authenticated)::bigint as authenticated_visits
  from public.site_visit_events sve
  where sve.created_at >= now() - make_interval(days => greatest(coalesce(p_days, 30), 1) - 1)
  group by 1
  order by 1 asc;
end;
$$;

create or replace function public.staff_site_visit_top_pages(
  p_days integer default 30,
  p_limit integer default 8
)
returns table (
  page_path text,
  total_visits bigint,
  unique_visitors bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_staff_member() then
    raise exception 'Access denied'
      using errcode = '42501';
  end if;

  return query
  select
    sve.page_path,
    count(*)::bigint as total_visits,
    count(distinct sve.visitor_key)::bigint as unique_visitors
  from public.site_visit_events sve
  where sve.created_at >= now() - make_interval(days => greatest(coalesce(p_days, 30), 1) - 1)
  group by sve.page_path
  order by count(*) desc, sve.page_path asc
  limit greatest(coalesce(p_limit, 8), 1);
end;
$$;

grant execute on function public.is_staff_member() to authenticated;
grant execute on function public.record_site_visit(text, text, text, text) to anon, authenticated;
grant execute on function public.staff_user_activity_summary(integer, bigint) to authenticated;
grant execute on function public.staff_site_visit_daily(integer) to authenticated;
grant execute on function public.staff_site_visit_top_pages(integer, integer) to authenticated;
