create table if not exists public.product_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text,
  group_key text not null default 'general',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default timezone('utc'::text, now())
);

create index if not exists product_categories_active_sort_idx
  on public.product_categories (is_active, sort_order, name);

alter table public.product_categories enable row level security;

drop policy if exists "Public product category read" on public.product_categories;
create policy "Public product category read"
on public.product_categories
for select
to public
using (is_active = true);

drop policy if exists "Admin manage product categories" on public.product_categories;
create policy "Admin manage product categories"
on public.product_categories
for all
to authenticated
using (get_admin_role() is not null)
with check (get_admin_role() is not null);

with source_categories as (
  select trim(name) as name, icon
  from public.categories
  where coalesce(trim(name), '') <> ''

  union
  select 'Home & Kitchen', null

  union
  select 'Sports', null

  union
  select 'Health & Fitness', null
),
normalized as (
  select
    name,
    max(icon) as icon,
    case
      when name in ('Mobile Phones & Accessories', 'Computers & IT Services', 'Electronics & Appliances') then 'tech'
      when name in ('Fashion & Apparel') then 'fashion'
      when name in (
        'Groceries & Supermarkets',
        'Beauty & Personal Care',
        'Pharmacies & Health Shops',
        'Food & Drinks',
        'Agriculture & Agro-Allied'
      ) then 'consumables'
      when name in ('Real Estate & Properties', 'Hotels & Accommodations') then 'property'
      else 'general'
    end as group_key,
    case
      when name = 'Mobile Phones & Accessories' then 10
      when name = 'Computers & IT Services' then 20
      when name = 'Electronics & Appliances' then 30
      when name = 'Fashion & Apparel' then 40
      when name = 'Groceries & Supermarkets' then 50
      when name = 'Beauty & Personal Care' then 60
      when name = 'Pharmacies & Health Shops' then 70
      when name = 'Food & Drinks' then 80
      when name = 'Agriculture & Agro-Allied' then 90
      when name = 'Real Estate & Properties' then 100
      when name = 'Hotels & Accommodations' then 110
      when name = 'Home & Kitchen' then 120
      when name = 'Sports' then 130
      when name = 'Health & Fitness' then 140
      when name = 'Logistics & Delivery' then 150
      when name = 'Education & Training' then 160
      when name = 'Artisans' then 170
      else 999
    end as sort_order
  from source_categories
  group by name
)
insert into public.product_categories (name, icon, group_key, sort_order, is_active)
select
  normalized.name,
  normalized.icon,
  normalized.group_key,
  normalized.sort_order,
  true
from normalized
on conflict (name) do update
set
  icon = excluded.icon,
  group_key = excluded.group_key,
  sort_order = excluded.sort_order,
  is_active = true;
