create extension if not exists postgis;

create table if not exists public.kyc_state_boundaries (
  id bigint generated by default as identity primary key,
  state_name text not null unique,
  state_code text,
  source_name text,
  source_boundary_id text,
  boundary geometry(MultiPolygon, 4326) not null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now())
);

create index if not exists kyc_state_boundaries_active_idx
  on public.kyc_state_boundaries (is_active, state_name);

create index if not exists kyc_state_boundaries_boundary_gix
  on public.kyc_state_boundaries
  using gist (boundary);

alter table public.kyc_state_boundaries enable row level security;

drop policy if exists "Public read KYC state boundaries" on public.kyc_state_boundaries;
create policy "Public read KYC state boundaries"
on public.kyc_state_boundaries
for select
to public
using (is_active = true);

drop policy if exists "Admin manage KYC state boundaries" on public.kyc_state_boundaries;
create policy "Admin manage KYC state boundaries"
on public.kyc_state_boundaries
for all
to authenticated
using (get_admin_role() is not null)
with check (get_admin_role() is not null);

create table if not exists public.kyc_gps_audits (
  id bigint generated by default as identity primary key,
  shop_id bigint not null references public.shops(id) on delete cascade,
  merchant_id uuid not null references public.profiles(id) on delete cascade,
  expected_state_name text,
  matched_state_name text,
  gps_point geography(Point, 4326) not null,
  latitude double precision not null,
  longitude double precision not null,
  inside_expected_state boolean not null default false,
  nearest_state_name text,
  nearest_state_distance_km numeric(10, 3),
  boundary_source text,
  captured_at timestamp with time zone not null default timezone('utc'::text, now()),
  created_at timestamp with time zone not null default timezone('utc'::text, now())
);

create index if not exists kyc_gps_audits_shop_id_idx
  on public.kyc_gps_audits (shop_id, captured_at desc);

create index if not exists kyc_gps_audits_merchant_id_idx
  on public.kyc_gps_audits (merchant_id, captured_at desc);

create index if not exists kyc_gps_audits_point_gix
  on public.kyc_gps_audits
  using gist (gps_point);

alter table public.kyc_gps_audits enable row level security;

drop policy if exists "Merchant insert own KYC GPS audit" on public.kyc_gps_audits;
create policy "Merchant insert own KYC GPS audit"
on public.kyc_gps_audits
for insert
to authenticated
with check (merchant_id = auth.uid());

drop policy if exists "Merchant view own KYC GPS audit" on public.kyc_gps_audits;
create policy "Merchant view own KYC GPS audit"
on public.kyc_gps_audits
for select
to authenticated
using (
  merchant_id = auth.uid()
  or get_admin_role() is not null
);

drop policy if exists "Admin manage KYC GPS audits" on public.kyc_gps_audits;
create policy "Admin manage KYC GPS audits"
on public.kyc_gps_audits
for all
to authenticated
using (get_admin_role() is not null)
with check (get_admin_role() is not null);

create or replace function public.touch_kyc_state_boundaries_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

drop trigger if exists trg_touch_kyc_state_boundaries_updated_at on public.kyc_state_boundaries;
create trigger trg_touch_kyc_state_boundaries_updated_at
before update on public.kyc_state_boundaries
for each row
execute function public.touch_kyc_state_boundaries_updated_at();

create or replace function public.record_kyc_gps_audit(
  p_shop_id bigint,
  p_merchant_id uuid,
  p_latitude double precision,
  p_longitude double precision
)
returns public.kyc_gps_audits
language plpgsql
security definer
set search_path = public
as $$
declare
  v_expected_state text;
  v_point geography(Point, 4326);
  v_inside public.kyc_state_boundaries%rowtype;
  v_nearest public.kyc_state_boundaries%rowtype;
  v_distance_km numeric(10, 3);
  v_inserted public.kyc_gps_audits%rowtype;
begin
  if auth.uid() is distinct from p_merchant_id and get_admin_role() is null then
    raise exception 'Not allowed to record this GPS audit.';
  end if;

  select c.state
  into v_expected_state
  from public.shops s
  join public.cities c on c.id = s.city_id
  where s.id = p_shop_id
    and s.owner_id = p_merchant_id
  limit 1;

  if v_expected_state is null then
    raise exception 'Expected state could not be resolved for this shop.';
  end if;

  v_point := st_setsrid(st_makepoint(p_longitude, p_latitude), 4326)::geography;

  select *
  into v_inside
  from public.kyc_state_boundaries sb
  where sb.is_active = true
    and st_intersects(sb.boundary, st_setsrid(st_makepoint(p_longitude, p_latitude), 4326))
  limit 1;

  select *
  into v_nearest
  from public.kyc_state_boundaries sb
  where sb.is_active = true
  order by st_distance(sb.boundary::geography, v_point)
  limit 1;

  if v_nearest.id is not null then
    v_distance_km := round((st_distance(v_nearest.boundary::geography, v_point) / 1000.0)::numeric, 3);
  end if;

  insert into public.kyc_gps_audits (
    shop_id,
    merchant_id,
    expected_state_name,
    matched_state_name,
    gps_point,
    latitude,
    longitude,
    inside_expected_state,
    nearest_state_name,
    nearest_state_distance_km,
    boundary_source
  )
  values (
    p_shop_id,
    p_merchant_id,
    v_expected_state,
    v_inside.state_name,
    v_point,
    p_latitude,
    p_longitude,
    coalesce(v_inside.state_name = v_expected_state, false),
    coalesce(v_inside.state_name, v_nearest.state_name),
    v_distance_km,
    coalesce(v_inside.source_name, v_nearest.source_name)
  )
  returning *
  into v_inserted;

  return v_inserted;
end;
$$;

grant execute on function public.record_kyc_gps_audit(bigint, uuid, double precision, double precision) to authenticated;

comment on table public.kyc_state_boundaries is
'Pilot PostGIS state polygons for KYC GPS validation. Start with Kaduna and Plateau only on free tier.';

comment on table public.kyc_gps_audits is
'Stores the live KYC GPS point and its state-level validation result for admin review, using cities.state as the expected state.';

-- Import helper examples for Kaduna and Plateau.
-- Replace the GeoJSON payload strings below with the full Feature geometry JSON for each state.
--
-- insert into public.kyc_state_boundaries (
--   state_name,
--   state_code,
--   source_name,
--   source_boundary_id,
--   boundary
-- )
-- values
-- (
--   'Kaduna',
--   'NG-KD',
--   'geoBoundaries GRID3 ADM1 2022',
--   'NGA-ADM1-27671186',
--   st_multi(st_setsrid(st_geomfromgeojson('{ "type": "Polygon", "coordinates": [ ... ] }'), 4326))
-- ),
-- (
--   'Plateau',
--   'NG-PL',
--   'geoBoundaries GRID3 ADM1 2022',
--   'NGA-ADM1-27671186',
--   st_multi(st_setsrid(st_geomfromgeojson('{ "type": "Polygon", "coordinates": [ ... ] }'), 4326))
-- )
-- on conflict (state_name) do update
-- set
--   state_code = excluded.state_code,
--   source_name = excluded.source_name,
--   source_boundary_id = excluded.source_boundary_id,
--   boundary = excluded.boundary,
--   is_active = true;
