-- Rebuild shop analytics around a unified event stream so merchant and staff
-- dashboards share one source of truth for views, contacts, conversion, and
-- suspicious contact behavior.

CREATE TABLE IF NOT EXISTS public.shop_analytics_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id bigint NOT NULL REFERENCES public.shops(id) ON DELETE CASCADE,
  product_id bigint REFERENCES public.products(id) ON DELETE SET NULL,
  actor_user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  actor_name text,
  actor_email text,
  actor_phone text,
  event_type text NOT NULL,
  event_source text NOT NULL DEFAULT 'shop_detail',
  contact_status text,
  repo_ref text,
  device_fingerprint text,
  ip_address text,
  ip_country text,
  user_agent text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT ctm_shop_analytics_event_type_check
    CHECK (event_type IN ('shop_view', 'contact_whatsapp', 'contact_phone')),
  CONSTRAINT ctm_shop_analytics_contact_status_check
    CHECK (contact_status IS NULL OR contact_status IN ('opened', 'requested', 'failed'))
);

CREATE INDEX IF NOT EXISTS ctm_shop_analytics_events_shop_created_idx
  ON public.shop_analytics_events (shop_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ctm_shop_analytics_events_shop_event_created_idx
  ON public.shop_analytics_events (shop_id, event_type, created_at DESC);

CREATE INDEX IF NOT EXISTS ctm_shop_analytics_events_actor_user_idx
  ON public.shop_analytics_events (actor_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ctm_shop_analytics_events_actor_email_idx
  ON public.shop_analytics_events (actor_email, created_at DESC);

CREATE INDEX IF NOT EXISTS ctm_shop_analytics_events_ip_idx
  ON public.shop_analytics_events (ip_address, created_at DESC);

CREATE INDEX IF NOT EXISTS ctm_shop_analytics_events_device_idx
  ON public.shop_analytics_events (device_fingerprint, created_at DESC);

ALTER TABLE public.shop_analytics_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "CTM shop analytics insert" ON public.shop_analytics_events;
DROP POLICY IF EXISTS "CTM shop analytics select" ON public.shop_analytics_events;

CREATE POLICY "CTM shop analytics insert"
ON public.shop_analytics_events
FOR INSERT
TO public
WITH CHECK (
  shop_id IS NOT NULL
  AND (actor_user_id IS NULL OR actor_user_id = (SELECT auth.uid()))
);

CREATE POLICY "CTM shop analytics select"
ON public.shop_analytics_events
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.shops s
    WHERE s.id = shop_analytics_events.shop_id
      AND (
        s.owner_id = (SELECT auth.uid())
        OR (SELECT public.ctm_has_super_staff_access())
        OR (
          (SELECT public.ctm_has_staff_access())
          AND s.city_id = (SELECT public.ctm_current_staff_city_scope())
        )
      )
  )
);

CREATE OR REPLACE FUNCTION public.ctm_shop_analytics_actor_key(
  p_actor_user_id uuid,
  p_actor_email text,
  p_device_fingerprint text,
  p_ip_address text
)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path TO 'public'
AS $$
  SELECT COALESCE(
    NULLIF(p_actor_user_id::text, ''),
    NULLIF(lower(trim(COALESCE(p_actor_email, ''))), ''),
    NULLIF(trim(COALESCE(p_device_fingerprint, '')), ''),
    NULLIF(trim(COALESCE(p_ip_address, '')), ''),
    'guest'
  );
$$;

CREATE OR REPLACE FUNCTION public.log_shop_analytics_event(
  p_shop_id bigint,
  p_event_type text,
  p_product_id bigint DEFAULT NULL,
  p_event_source text DEFAULT 'shop_detail',
  p_contact_status text DEFAULT NULL,
  p_repo_ref text DEFAULT NULL,
  p_device_fingerprint text DEFAULT NULL,
  p_user_agent text DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_actor_id uuid := auth.uid();
  v_actor_name text := NULL;
  v_actor_email text := NULL;
  v_actor_phone text := NULL;
  v_network json := '{}'::json;
  v_headers jsonb := '{}'::jsonb;
  v_user_agent text := NULL;
  v_event_source text := COALESCE(NULLIF(trim(COALESCE(p_event_source, '')), ''), 'shop_detail');
  v_contact_status text := NULLIF(trim(COALESCE(p_contact_status, '')), '');
  v_actor_key text := 'guest';
  v_event_id bigint;
BEGIN
  IF p_shop_id IS NULL THEN
    RAISE EXCEPTION 'Shop id is required.' USING ERRCODE = '23502';
  END IF;

  IF p_event_type NOT IN ('shop_view', 'contact_whatsapp', 'contact_phone') THEN
    RAISE EXCEPTION 'Unsupported analytics event type.' USING ERRCODE = '22023';
  END IF;

  IF v_contact_status IS NOT NULL AND v_contact_status NOT IN ('opened', 'requested', 'failed') THEN
    RAISE EXCEPTION 'Unsupported contact status.' USING ERRCODE = '22023';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.shops WHERE id = p_shop_id) THEN
    RAISE EXCEPTION 'Shop not found.' USING ERRCODE = 'P0002';
  END IF;

  IF p_product_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM public.products
    WHERE id = p_product_id
      AND shop_id = p_shop_id
  ) THEN
    RAISE EXCEPTION 'Product does not belong to this shop.' USING ERRCODE = '22023';
  END IF;

  IF v_actor_id IS NOT NULL THEN
    SELECT
      p.full_name,
      p.phone,
      u.email
    INTO
      v_actor_name,
      v_actor_phone,
      v_actor_email
    FROM public.profiles p
    LEFT JOIN auth.users u ON u.id = p.id
    WHERE p.id = v_actor_id;
  END IF;

  BEGIN
    v_headers := COALESCE(current_setting('request.headers', true), '{}')::jsonb;
  EXCEPTION WHEN OTHERS THEN
    v_headers := '{}'::jsonb;
  END;

  v_network := public.get_network_info();
  v_user_agent := COALESCE(
    NULLIF(trim(COALESCE(p_user_agent, '')), ''),
    NULLIF(v_headers ->> 'user-agent', ''),
    NULLIF(v_headers ->> 'User-Agent', '')
  );
  v_actor_key := public.ctm_shop_analytics_actor_key(
    v_actor_id,
    v_actor_email,
    p_device_fingerprint,
    v_network ->> 'ip'
  );

  IF p_event_type = 'shop_view' AND EXISTS (
    SELECT 1
    FROM public.shop_analytics_events e
    WHERE e.shop_id = p_shop_id
      AND e.event_type = p_event_type
      AND e.event_source = v_event_source
      AND e.created_at >= now() - INTERVAL '15 minutes'
      AND public.ctm_shop_analytics_actor_key(
        e.actor_user_id,
        e.actor_email,
        e.device_fingerprint,
        e.ip_address
      ) = v_actor_key
  ) THEN
    RETURN jsonb_build_object('logged', false, 'deduped', true);
  END IF;

  IF p_event_type IN ('contact_whatsapp', 'contact_phone') AND EXISTS (
    SELECT 1
    FROM public.shop_analytics_events e
    WHERE e.shop_id = p_shop_id
      AND e.product_id IS NOT DISTINCT FROM p_product_id
      AND e.event_type = p_event_type
      AND e.created_at >= now() - INTERVAL '8 seconds'
      AND public.ctm_shop_analytics_actor_key(
        e.actor_user_id,
        e.actor_email,
        e.device_fingerprint,
        e.ip_address
      ) = v_actor_key
  ) THEN
    RETURN jsonb_build_object('logged', false, 'deduped', true);
  END IF;

  INSERT INTO public.shop_analytics_events (
    shop_id,
    product_id,
    actor_user_id,
    actor_name,
    actor_email,
    actor_phone,
    event_type,
    event_source,
    contact_status,
    repo_ref,
    device_fingerprint,
    ip_address,
    ip_country,
    user_agent,
    metadata
  )
  VALUES (
    p_shop_id,
    p_product_id,
    v_actor_id,
    v_actor_name,
    v_actor_email,
    v_actor_phone,
    p_event_type,
    v_event_source,
    v_contact_status,
    NULLIF(trim(COALESCE(p_repo_ref, '')), ''),
    NULLIF(trim(COALESCE(p_device_fingerprint, '')), ''),
    NULLIF(v_network ->> 'ip', 'Unknown IP'),
    NULLIF(v_network ->> 'country', 'Unknown'),
    v_user_agent,
    COALESCE(p_metadata, '{}'::jsonb)
  )
  RETURNING id INTO v_event_id;

  RETURN jsonb_build_object('logged', true, 'event_id', v_event_id);
END;
$$;

GRANT EXECUTE ON FUNCTION public.log_shop_analytics_event(bigint, text, bigint, text, text, text, text, text, jsonb) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.ctm_get_shop_analytics_summary(
  p_shop_id bigint,
  p_days integer DEFAULT 30
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_days integer := GREATEST(COALESCE(p_days, 30), 1);
  v_window_start timestamp with time zone := now() - make_interval(days => GREATEST(COALESCE(p_days, 30), 1) - 1);
  v_has_access boolean := false;
BEGIN
  SELECT EXISTS (
    SELECT 1
    FROM public.shops s
    WHERE s.id = p_shop_id
      AND (
        s.owner_id = (SELECT auth.uid())
        OR (SELECT public.ctm_has_super_staff_access())
        OR (
          (SELECT public.ctm_has_staff_access())
          AND s.city_id = (SELECT public.ctm_current_staff_city_scope())
        )
      )
  ) INTO v_has_access;

  IF NOT v_has_access THEN
    RAISE EXCEPTION 'Access denied.' USING ERRCODE = '42501';
  END IF;

  RETURN (
    WITH shop_meta AS (
      SELECT
        s.id,
        s.name,
        s.unique_id,
        s.city_id,
        c.name AS city_name
      FROM public.shops s
      LEFT JOIN public.cities c ON c.id = s.city_id
      WHERE s.id = p_shop_id
    ),
    scoped_events AS (
      SELECT
        e.*,
        timezone('Africa/Lagos', e.created_at)::date AS event_date,
        public.ctm_shop_analytics_actor_key(
          e.actor_user_id,
          e.actor_email,
          e.device_fingerprint,
          e.ip_address
        ) AS actor_key
      FROM public.shop_analytics_events e
      WHERE e.shop_id = p_shop_id
        AND e.created_at >= v_window_start
    ),
    opened_contacts AS (
      SELECT *
      FROM scoped_events
      WHERE event_type IN ('contact_whatsapp', 'contact_phone')
        AND COALESCE(contact_status, 'opened') = 'opened'
    ),
    daily_rollup AS (
      SELECT
        gs::date AS event_date,
        COALESCE(count(*) FILTER (WHERE e.event_type = 'shop_view'), 0)::bigint AS views,
        COALESCE(count(*) FILTER (WHERE e.event_type = 'shop_view' AND e.event_source = 'repo_search'), 0)::bigint AS repo_search_views,
        COALESCE(count(*) FILTER (WHERE e.event_type IN ('contact_whatsapp', 'contact_phone') AND COALESCE(e.contact_status, 'opened') = 'opened'), 0)::bigint AS contacts,
        COALESCE(count(*) FILTER (WHERE e.event_type = 'contact_whatsapp' AND COALESCE(e.contact_status, 'opened') = 'opened'), 0)::bigint AS whatsapp_contacts,
        COALESCE(count(*) FILTER (WHERE e.event_type = 'contact_phone' AND COALESCE(e.contact_status, 'opened') = 'opened'), 0)::bigint AS phone_contacts
      FROM generate_series(
        timezone('Africa/Lagos', v_window_start)::date,
        timezone('Africa/Lagos', now())::date,
        INTERVAL '1 day'
      ) AS gs
      LEFT JOIN scoped_events e ON e.event_date = gs::date
      GROUP BY gs
      ORDER BY gs
    ),
    actor_rollup AS (
      SELECT
        actor_key,
        (
          array_agg(actor_user_id ORDER BY created_at DESC NULLS LAST)
          FILTER (WHERE actor_user_id IS NOT NULL)
        )[1] AS actor_user_id,
        max(NULLIF(actor_name, '')) AS actor_name,
        max(NULLIF(actor_email, '')) AS actor_email,
        max(NULLIF(actor_phone, '')) AS actor_phone,
        max(NULLIF(ip_address, '')) AS ip_address,
        max(NULLIF(device_fingerprint, '')) AS device_fingerprint,
        count(*)::bigint AS total_contacts,
        count(*) FILTER (WHERE event_type = 'contact_whatsapp')::bigint AS whatsapp_contacts,
        count(*) FILTER (WHERE event_type = 'contact_phone')::bigint AS phone_contacts,
        max(created_at) AS latest_contact_at,
        count(DISTINCT product_id)::bigint AS distinct_products,
        CASE
          WHEN count(*) >= 8 THEN 'critical'
          WHEN count(*) >= 5 THEN 'high'
          WHEN count(*) >= 3 THEN 'medium'
          ELSE 'low'
        END AS risk_level
      FROM opened_contacts
      GROUP BY actor_key
    ),
    contact_feed_rollup AS (
      SELECT DISTINCT ON (e.actor_key)
        e.actor_key,
        e.id,
        e.event_type,
        e.event_source,
        e.product_id,
        e.created_at,
        NULLIF(e.ip_address, '') AS ip_address,
        NULLIF(e.device_fingerprint, '') AS device_fingerprint
      FROM opened_contacts e
      ORDER BY e.actor_key, e.created_at DESC, e.id DESC
    ),
    totals AS (
      SELECT
        count(*) FILTER (WHERE event_type = 'shop_view')::bigint AS total_views,
        count(*) FILTER (WHERE event_type = 'shop_view' AND event_source = 'repo_search')::bigint AS repo_search_views,
        count(*) FILTER (WHERE event_type IN ('contact_whatsapp', 'contact_phone') AND COALESCE(contact_status, 'opened') = 'opened')::bigint AS total_contacts,
        count(*) FILTER (WHERE event_type = 'contact_whatsapp' AND COALESCE(contact_status, 'opened') = 'opened')::bigint AS whatsapp_contacts,
        count(*) FILTER (WHERE event_type = 'contact_phone' AND COALESCE(contact_status, 'opened') = 'opened')::bigint AS phone_contacts,
        count(DISTINCT actor_key) FILTER (
          WHERE event_type IN ('contact_whatsapp', 'contact_phone')
            AND COALESCE(contact_status, 'opened') = 'opened'
        )::bigint AS unique_contact_actors
      FROM scoped_events
    )
    SELECT jsonb_build_object(
      'shop', (
        SELECT jsonb_build_object(
          'id', shop_meta.id,
          'name', shop_meta.name,
          'unique_id', shop_meta.unique_id,
          'city_name', shop_meta.city_name
        )
        FROM shop_meta
      ),
      'window_days', v_days,
      'totals', (
        SELECT jsonb_build_object(
          'views', total_views,
          'repo_search_views', repo_search_views,
          'contacts', total_contacts,
          'whatsapp_contacts', whatsapp_contacts,
          'phone_contacts', phone_contacts,
          'unique_contact_actors', unique_contact_actors,
          'conversion_rate',
            CASE
              WHEN total_views > 0
                THEN round((total_contacts::numeric / total_views::numeric) * 100, 1)
              ELSE 0
            END
        )
        FROM totals
      ),
      'timeline', (
        SELECT COALESCE(jsonb_agg(row_to_json(daily_rollup) ORDER BY daily_rollup.event_date), '[]'::jsonb)
        FROM daily_rollup
      ),
      'recent_contacts', (
        SELECT COALESCE(jsonb_agg(row_to_json(contact_row) ORDER BY contact_row.created_at DESC), '[]'::jsonb)
        FROM (
          SELECT
            cf.id::bigint AS id,
            COALESCE(ar.actor_name, 'Guest visitor') AS actor_name,
            ar.actor_email,
            ar.actor_phone,
            ar.actor_user_id,
            cf.event_type,
            cf.event_source,
            'opened'::text AS contact_status,
            cf.created_at,
            cf.ip_address,
            cf.device_fingerprint,
            p.name AS product_name,
            ar.total_contacts AS actor_contact_count,
            ar.risk_level
          FROM contact_feed_rollup cf
          LEFT JOIN public.products p ON p.id = cf.product_id
          LEFT JOIN actor_rollup ar ON ar.actor_key = cf.actor_key
          ORDER BY cf.created_at DESC
          LIMIT 40
        ) AS contact_row
      ),
      'suspicious_contacts', (
        SELECT COALESCE(jsonb_agg(row_to_json(actor_row) ORDER BY actor_row.total_contacts DESC, actor_row.latest_contact_at DESC), '[]'::jsonb)
        FROM (
          SELECT
            actor_key,
            COALESCE(actor_name, 'Guest visitor') AS actor_name,
            actor_email,
            actor_phone,
            actor_user_id,
            ip_address,
            device_fingerprint,
            total_contacts,
            whatsapp_contacts,
            phone_contacts,
            distinct_products,
            latest_contact_at,
            risk_level
          FROM actor_rollup
          WHERE total_contacts >= 3
        ) AS actor_row
      )
    )
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.ctm_get_shop_analytics_summary(bigint, integer) TO authenticated;

CREATE OR REPLACE FUNCTION public.ctm_get_staff_shop_analytics(
  p_days integer DEFAULT 30,
  p_city_id bigint DEFAULT NULL,
  p_limit integer DEFAULT 50
)
RETURNS TABLE (
  shop_id bigint,
  shop_name text,
  unique_id text,
  city_name text,
  owner_name text,
  total_views bigint,
  repo_search_views bigint,
  total_contacts bigint,
  whatsapp_contacts bigint,
  phone_contacts bigint,
  conversion_rate numeric,
  latest_contact_at timestamp with time zone,
  suspicious_actor_count bigint,
  risk_level text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_days integer := GREATEST(COALESCE(p_days, 30), 1);
  v_window_start timestamp with time zone := now() - make_interval(days => GREATEST(COALESCE(p_days, 30), 1) - 1);
  v_effective_city_id bigint := NULL;
BEGIN
  IF NOT (SELECT public.ctm_has_staff_access()) THEN
    RAISE EXCEPTION 'Access denied.' USING ERRCODE = '42501';
  END IF;

  IF (SELECT public.ctm_has_super_staff_access()) THEN
    v_effective_city_id := p_city_id;
  ELSE
    v_effective_city_id := (SELECT public.ctm_current_staff_city_scope());
    IF v_effective_city_id IS NULL THEN
      RAISE EXCEPTION 'Staff city scope is missing.' USING ERRCODE = '42501';
    END IF;
  END IF;

  RETURN QUERY
  WITH scoped_events AS (
    SELECT
      e.*,
      public.ctm_shop_analytics_actor_key(
        e.actor_user_id,
        e.actor_email,
        e.device_fingerprint,
        e.ip_address
      ) AS actor_key
    FROM public.shop_analytics_events e
    JOIN public.shops s ON s.id = e.shop_id
    WHERE e.created_at >= v_window_start
      AND (v_effective_city_id IS NULL OR s.city_id = v_effective_city_id)
  ),
  actor_risk AS (
    SELECT
      shop_id,
      actor_key,
      count(*) FILTER (
        WHERE event_type IN ('contact_whatsapp', 'contact_phone')
          AND COALESCE(contact_status, 'opened') = 'opened'
      )::bigint AS total_contacts
    FROM scoped_events
    GROUP BY shop_id, actor_key
  ),
  suspicious_counts AS (
    SELECT
      shop_id,
      count(*) FILTER (WHERE total_contacts >= 3)::bigint AS suspicious_actor_count
    FROM actor_risk
    GROUP BY shop_id
  ),
  shop_totals AS (
    SELECT
      s.id AS shop_id,
      s.name AS shop_name,
      s.unique_id,
      c.name AS city_name,
      owner.full_name AS owner_name,
      count(*) FILTER (WHERE e.event_type = 'shop_view')::bigint AS total_views,
      count(*) FILTER (WHERE e.event_type = 'shop_view' AND e.event_source = 'repo_search')::bigint AS repo_search_views,
      count(*) FILTER (
        WHERE e.event_type IN ('contact_whatsapp', 'contact_phone')
          AND COALESCE(e.contact_status, 'opened') = 'opened'
      )::bigint AS total_contacts,
      count(*) FILTER (
        WHERE e.event_type = 'contact_whatsapp'
          AND COALESCE(e.contact_status, 'opened') = 'opened'
      )::bigint AS whatsapp_contacts,
      count(*) FILTER (
        WHERE e.event_type = 'contact_phone'
          AND COALESCE(e.contact_status, 'opened') = 'opened'
      )::bigint AS phone_contacts,
      max(e.created_at) FILTER (
        WHERE e.event_type IN ('contact_whatsapp', 'contact_phone')
          AND COALESCE(e.contact_status, 'opened') = 'opened'
      ) AS latest_contact_at
    FROM public.shops s
    LEFT JOIN public.cities c ON c.id = s.city_id
    LEFT JOIN public.profiles owner ON owner.id = s.owner_id
    LEFT JOIN scoped_events e ON e.shop_id = s.id
    WHERE v_effective_city_id IS NULL OR s.city_id = v_effective_city_id
    GROUP BY s.id, s.name, s.unique_id, c.name, owner.full_name
  )
  SELECT
    st.shop_id,
    st.shop_name,
    st.unique_id,
    st.city_name,
    st.owner_name,
    st.total_views,
    st.repo_search_views,
    st.total_contacts,
    st.whatsapp_contacts,
    st.phone_contacts,
    CASE
      WHEN st.total_views > 0
        THEN round((st.total_contacts::numeric / st.total_views::numeric) * 100, 1)
      ELSE 0
    END AS conversion_rate,
    st.latest_contact_at,
    COALESCE(sc.suspicious_actor_count, 0)::bigint AS suspicious_actor_count,
    CASE
      WHEN COALESCE(sc.suspicious_actor_count, 0) >= 3 OR st.total_contacts >= 20 THEN 'critical'
      WHEN COALESCE(sc.suspicious_actor_count, 0) >= 1 OR st.total_contacts >= 10 THEN 'high'
      WHEN st.total_contacts >= 5 OR st.total_views >= 20 THEN 'medium'
      ELSE 'low'
    END AS risk_level
  FROM shop_totals st
  LEFT JOIN suspicious_counts sc ON sc.shop_id = st.shop_id
  WHERE st.total_views > 0 OR st.total_contacts > 0
  ORDER BY st.total_contacts DESC, st.total_views DESC, st.shop_name ASC
  LIMIT GREATEST(COALESCE(p_limit, 50), 1);
END;
$$;

GRANT EXECUTE ON FUNCTION public.ctm_get_staff_shop_analytics(integer, bigint, integer) TO authenticated;

CREATE OR REPLACE FUNCTION public.ctm_get_contact_security_radar(
  p_days integer DEFAULT 30,
  p_city_id bigint DEFAULT NULL
)
RETURNS TABLE (
  actor_key text,
  actor_name text,
  actor_email text,
  actor_phone text,
  actor_user_id uuid,
  total_contacts bigint,
  whatsapp_contacts bigint,
  phone_contacts bigint,
  distinct_shops bigint,
  latest_contact_at timestamp with time zone,
  primary_ip text,
  device_fingerprint text,
  risk_level text,
  shops jsonb
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_window_start timestamp with time zone := now() - make_interval(days => GREATEST(COALESCE(p_days, 30), 1) - 1);
  v_effective_city_id bigint := NULL;
BEGIN
  IF NOT (SELECT public.ctm_has_staff_access()) THEN
    RAISE EXCEPTION 'Access denied.' USING ERRCODE = '42501';
  END IF;

  IF (SELECT public.ctm_has_super_staff_access()) THEN
    v_effective_city_id := p_city_id;
  ELSE
    v_effective_city_id := (SELECT public.ctm_current_staff_city_scope());
    IF v_effective_city_id IS NULL THEN
      RAISE EXCEPTION 'Staff city scope is missing.' USING ERRCODE = '42501';
    END IF;
  END IF;

  RETURN QUERY
  WITH scoped_contacts AS (
    SELECT
      e.*,
      s.name AS shop_name,
      s.unique_id,
      public.ctm_shop_analytics_actor_key(
        e.actor_user_id,
        e.actor_email,
        e.device_fingerprint,
        e.ip_address
      ) AS resolved_actor_key
    FROM public.shop_analytics_events e
    JOIN public.shops s ON s.id = e.shop_id
    WHERE e.created_at >= v_window_start
      AND e.event_type IN ('contact_whatsapp', 'contact_phone')
      AND COALESCE(e.contact_status, 'opened') = 'opened'
      AND (v_effective_city_id IS NULL OR s.city_id = v_effective_city_id)
  ),
  actor_rollup AS (
    SELECT
      resolved_actor_key AS actor_key,
      (
        array_agg(sc.actor_user_id ORDER BY sc.created_at DESC NULLS LAST)
        FILTER (WHERE sc.actor_user_id IS NOT NULL)
      )[1] AS actor_user_id,
      max(NULLIF(sc.actor_name, '')) AS actor_name,
      max(NULLIF(sc.actor_email, '')) AS actor_email,
      max(NULLIF(sc.actor_phone, '')) AS actor_phone,
      max(NULLIF(sc.ip_address, '')) AS primary_ip,
      max(NULLIF(sc.device_fingerprint, '')) AS device_fingerprint,
      count(*)::bigint AS total_contacts,
      count(*) FILTER (WHERE sc.event_type = 'contact_whatsapp')::bigint AS whatsapp_contacts,
      count(*) FILTER (WHERE sc.event_type = 'contact_phone')::bigint AS phone_contacts,
      count(DISTINCT sc.shop_id)::bigint AS distinct_shops,
      max(sc.created_at) AS latest_contact_at
    FROM scoped_contacts sc
    GROUP BY resolved_actor_key
  ),
  shop_breakdown AS (
    SELECT
      sc.resolved_actor_key AS actor_key,
      sc.shop_id,
      max(sc.shop_name) AS shop_name,
      max(sc.unique_id) AS unique_id,
      count(*)::bigint AS contacts,
      max(sc.created_at) AS latest_contact_at
    FROM scoped_contacts sc
    GROUP BY sc.resolved_actor_key, sc.shop_id
  )
  SELECT
    ar.actor_key,
    COALESCE(ar.actor_name, 'Guest visitor') AS actor_name,
    ar.actor_email,
    ar.actor_phone,
    ar.actor_user_id,
    ar.total_contacts,
    ar.whatsapp_contacts,
    ar.phone_contacts,
    ar.distinct_shops,
    ar.latest_contact_at,
    ar.primary_ip,
    ar.device_fingerprint,
    CASE
      WHEN ar.total_contacts >= 12 OR ar.distinct_shops >= 4 THEN 'critical'
      WHEN ar.total_contacts >= 8 OR ar.distinct_shops >= 3 THEN 'high'
      WHEN ar.total_contacts >= 4 OR ar.distinct_shops >= 2 THEN 'medium'
      ELSE 'low'
    END AS risk_level,
    COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object(
          'shop_id', sb.shop_id,
          'shop_name', sb.shop_name,
          'unique_id', sb.unique_id,
          'contacts', sb.contacts,
          'latest_contact_at', sb.latest_contact_at
        )
        ORDER BY sb.contacts DESC, sb.latest_contact_at DESC
      )
      FROM shop_breakdown sb
      WHERE sb.actor_key = ar.actor_key
    ), '[]'::jsonb) AS shops
  FROM actor_rollup ar
  WHERE ar.total_contacts >= 3
  ORDER BY ar.total_contacts DESC, ar.latest_contact_at DESC;
END;
$$;

GRANT EXECUTE ON FUNCTION public.ctm_get_contact_security_radar(integer, bigint) TO authenticated;
